auto_mode: true
backtest_end: '2026-06-08'
backtest_start: '2026-05-01'
ema_fast: 20
ema_slow: 30
htf_ema_fast: 9
htf_ema_slow: 21
htf_enabled: true
htf_timeframe: 1h
leverage: 100
log_file: logs/sol.log
mode: live
paper_balance: 1000.0
risk_pct: 3.0
sl_pct: 1.5
symbol: SOLUSDT
timeframe: 5m
tp1_close_pct: 30
tp1_pct: 0.35000000000000003
tp2_pct: 0.75
volume_ma_period: 20
volume_multiplier: 1.9
