auto_mode: true
backtest_end: '2026-06-08'
backtest_start: '2026-05-01'
ema_fast: 7
ema_slow: 15
htf_ema_fast: 7
htf_ema_slow: 21
htf_enabled: false
htf_timeframe: 1h
leverage: 50
log_file: logs/pepe.log
mode: live
paper_balance: 1000.0
risk_pct: 3.0
sl_pct: 2.0
symbol: 1000PEPEUSDT
timeframe: 5m
tp1_close_pct: 60
tp1_pct: 0.7
tp2_pct: 1.0
volume_ma_period: 20
volume_multiplier: 1.5

fixed_qty: 0
