auto_mode: true
backtest_end: '2026-06-08'
backtest_start: '2026-05-01'
ema_fast: 5
ema_slow: 13
htf_ema_fast: 14
htf_ema_slow: 20
htf_enabled: true
htf_timeframe: 1h
leverage: 50
log_file: logs/pepe.log
mode: live
paper_balance: 1000.0
sl_pct: 0.2
symbol: 1000PEPEUSDT
timeframe: 5m
tp1_close_pct: 100
tp1_pct: 0.4
tp2_pct: 0.4
volume_ma_period: 20
volume_multiplier: 2.3

fixed_notional_usd: 1.0
fixed_qty: 0.0
fixed_risk_usd: 0
risk_pct: 3.0
