auto_mode: true
backtest_end: '2026-06-08'
backtest_start: '2026-05-01'
ema_fast: 6
ema_slow: 9
htf_ema_fast: 9
htf_ema_slow: 21
htf_enabled: true
htf_timeframe: 1h
leverage: 110
log_file: logs/bnb.log
mode: live
paper_balance: 1000.0
risk_pct: 1.0
sl_pct: 1.3
symbol: BNBUSDT
timeframe: 5m
tp1_close_pct: 50
tp1_pct: 0.95
tp2_pct: 2.45
volume_ma_period: 20
volume_multiplier: 1.1
