auto_mode: true
backtest_end: '2026-06-08'
backtest_start: '2026-05-01'
ema_fast: 11
ema_slow: 15
htf_ema_fast: 11
htf_ema_slow: 25
htf_enabled: false
htf_timeframe: 1h
leverage: 100
log_file: logs/ada.log
mode: live
paper_balance: 1000.0
risk_pct: 5.0
sl_pct: 1.35
symbol: ADAUSDT
timeframe: 5m
tp1_close_pct: 60
tp1_pct: 0.5
tp2_pct: 0.7
volume_ma_period: 20
volume_multiplier: 1.9
