auto_mode: true
backtest_end: '2026-06-08'
backtest_start: '2026-05-01'
ema_fast: 13
ema_slow: 24
htf_ema_fast: 15
htf_ema_slow: 24
htf_enabled: true
htf_timeframe: 1h
leverage: 75
log_file: logs/inj.log
mode: live
paper_balance: 1000.0
risk_pct: 3
sl_pct: 1.1
symbol: INJUSDT
timeframe: 5m
tp1_close_pct: 70
tp1_pct: 0.4
tp2_pct: 1.5
volume_ma_period: 20
volume_multiplier: 1.9
