auto_mode: true
backtest_end: '2026-06-15'
backtest_start: '2026-06-01'
ema_fast: 15
ema_slow: 53
htf_ema_fast: 9
htf_ema_slow: 21
htf_enabled: true
htf_timeframe: 1h
leverage: 100
log_file: logs/ont.log
mode: live
paper_balance: 1000.0
risk_pct: 5
sl_pct: 0.30000000000000004
symbol: ONTUSDT
timeframe: 5m
tp1_close_pct: 50
tp1_pct: 0.2
tp2_pct: 0.3
volume_ma_period: 20
volume_multiplier: 1.1
